dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: ttc-dashboard-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- name: ttc-infra-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.13
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.8.0
- name: ttc-connectors-dummytwitter
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.42
- name: ttc-rb-english-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
